### ISSUE TITLE
HAL spec conformity, drop nested-fields dependency

### ISSUE THREAD

**Issue by jstaffans** [seebass/drf-hal-json#5]
Thanks for your work on this! Not much work has gone into HATEOAS in DRF-land, so this is much appreciated.

We used this library as a starting point for our own version, see https://github.com/Artory/drf-hal-json. Some of the things we changed:

- Fix the issue with custom `lookup_field` (#3)
- conform to HAL spec by rendering links as objects with a `href` attribute (`{"self": {"href": "..."}}`)
- Drop the nested-fields dependency since this is not part of the spec
- Support pagination
- Simplify implementation by removing nested serializers, instead we do everything in `to_representation`
- Refactor tests and add a Makefile for ease of development

Since the end result is basically a complete re-write, I wanted to ask if you are open to accepting a PR for this? If not, we will probably eventually push a separate PyPi package under a different name.

**Comment by seebass** [comment]
Hi, 
that sounds good. I was not totally happy with the implementation and your approach simplifies it a lot. For my projects I need to find a way to make it work in conjunction with the nested-fields package, but I will figure that out. Please add a PR. Thanks for your work.
