### ISSUE TITLE
Respect (or error on) Serializer Fields for Related Objects

### ISSUE THREAD

**Issue by ambsw-technology** [seebass/drf-hal-json#8]
Given two related items:

    class Patient(models.Model):
        ...
    
    class Event(models.Model):
        patient = models.ForeignKey(Patient)

I want to include a link to the events list rather than to the individual events.  With the ModelSerializer (and `drf-nested-routers`), I can add a field like:

    event_set = HyperlinkedIdentityField(
        view_name='patient-event-list',
        lookup_url_kwarg='patient_pk',
        lookup_field='pk',
        read_only=True,
    )

... and get the output:

    {
        ...
        "event_set": "http://localhost:8085/api/patients/2/events/"
    }

When I switch to the HalModelSerializer, I instead get:

    {
        "_links": {
            ...
            "event_set": []
        },
        ... (no event_set entry)
    }

This does not seem like the right behavior.  Some ideas include:

 - raise `ImproperlyConfigured` if a field for the `_set` is found on the serializer
 - respect (and display) the field (as defined) in the embed
 - respect (and display) the field (as defined) in the _links
 - display the field (as defined) in the links if the field is a `HyperlinkedRelatedField` (or descendant) and in the embed otherwise

FWIW I'm actually including the link to support related event creation so it probably *should* be in the _links section.

**Comment by claytondaley** [comment]
already resolved in actively developed fork [Artory/drf-hal-json](https://github.com/Artory/drf-hal-json)

**Comment by ambsw-technology** [comment]
already resolved in actively developed fork [Artory/drf-hal-json](https://github.com/Artory/drf-hal-json)
